name: ltspice-ci

on: [push, pull_request]

jobs:
  ltspice:
    runs-on: ubuntu-latest
    container: aanas0sayed/docker-ltspice
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Environment variables
        run: |
          export DISPLAY=:0.0
          export WINEDEBUG=fixme-all,err-all,warn-all
      - name: Preparations
        run: |
          sudo rm -rf ~/docker-data/wine
          sudo mkdir -p ~/docker-data/wine
      - name: Run LTspice
        run: |
          sudo xvfb-run -a wine64 "/root/.wine/drive_c/Program Files/ADI/LTspice/Ltspice.exe" -b -Run ./ltspice/freq_resp.asc
          ls -al ./ltspice
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ltspice
          path: |
            ./ltspice/freq_resp.log
            ./ltspice/freq_resp.raw
          retention-days: 7
    
  report:
    needs: ltspice
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
      - name: Python packages
        run: |
          pip install PyLTSpice numpy pandas tabulate Pygments
      - name: Extract data
        run: |
          cd script
          python3 freq_resp.py
          pygmentize -g freq_resp.md
      - name : CML
        run: |
          cd script
          pwd
          # Create CML report
          echo '![](./freq_resp.png "Frequency response plot")' >> freq_resp.md
          cml comment create freq_resp.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

